/**
 * Canonical audit actions.
 *
 * Every audit_logs row stores one of these names, written in the shared
 * SCREAMING_SNAKE vocabulary. Earlier phases stored dotted lowercase names
 * ("job.created"); each of those has a canonical form here and the services
 * that wrote them now write the canonical form, so what the audit API returns
 * is one consistent vocabulary.
 */
export const AUDIT_ACTIONS = {
  // Authentication and accounts
  USER_REGISTERED: 'USER_REGISTERED',
  AUTH_LOGIN: 'AUTH_LOGIN',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  AUTH_PASSWORD_RESET_REQUESTED: 'AUTH_PASSWORD_RESET_REQUESTED',
  AUTH_PASSWORD_RESET: 'AUTH_PASSWORD_RESET',
  AUTH_EMAIL_VERIFIED: 'AUTH_EMAIL_VERIFIED',
  AUTH_OAUTH_LINKED: 'AUTH_OAUTH_LINKED',

  // Profiles and files
  PROFILE_RESUME_SET: 'PROFILE_RESUME_SET',
  PROFILE_RESUME_CLEARED: 'PROFILE_RESUME_CLEARED',
  FILE_UPLOADED: 'FILE_UPLOADED',
  FILE_DELETED: 'FILE_DELETED',

  // Mentorship
  MENTORSHIP_REQUESTED: 'MENTORSHIP_REQUESTED',
  MENTORSHIP_ACCEPTED: 'MENTORSHIP_ACCEPTED',
  MENTORSHIP_DECLINED: 'MENTORSHIP_DECLINED',
  MENTORSHIP_REJECTED: 'MENTORSHIP_DECLINED',
  MENTORSHIP_CANCELLED: 'MENTORSHIP_CANCELLED',
  MENTORSHIP_ENDED: 'MENTORSHIP_ENDED',
  MENTORSHIP_COMPLETED: 'MENTORSHIP_COMPLETED',

  // Jobs and applications
  JOB_CREATED: 'JOB_CREATED',
  JOB_UPDATED: 'JOB_UPDATED',
  JOB_DELETED: 'JOB_DELETED',
  JOB_CLOSED: 'JOB_CLOSED',
  JOB_APPLIED: 'JOB_APPLIED',
  JOB_APPROVED: 'JOB_APPROVED',
  JOB_REJECTED: 'JOB_REJECTED',
  JOB_SUBMITTED: 'JOB_SUBMITTED',
  JOB_PENDING_REVIEW: 'JOB_SUBMITTED',
  APPLICATION_STATUS_CHANGED: 'APPLICATION_STATUS_CHANGED',
  APPLICATION_WITHDRAWN: 'APPLICATION_WITHDRAWN',

  // Alumni verification
  ALUMNI_VERIFIED: 'ALUMNI_VERIFIED',
  ALUMNI_REJECTED: 'ALUMNI_REJECTED',

  // Events
  EVENT_PUBLISHED: 'EVENT_PUBLISHED',
  EVENT_CANCELLED: 'EVENT_CANCELLED',
  EVENT_COMPLETED: 'EVENT_COMPLETED',

  // Donations and payments
  DONATION_CREATED: 'DONATION_CREATED',
  DONATION_CONFIRMED: 'DONATION_CONFIRMED',
  DONATION_RECEIPT_ISSUED: 'DONATION_RECEIPT_ISSUED',
  DONATION_REFUNDED: 'DONATION_REFUNDED',
  PAYMENT_WEBHOOK_RECEIVED: 'PAYMENT_WEBHOOK_RECEIVED',
  PAYMENT_WEBHOOK_REJECTED: 'PAYMENT_WEBHOOK_REJECTED',

  // Administration and moderation
  USER_SUSPENDED: 'USER_SUSPENDED',
  USER_REACTIVATED: 'USER_REACTIVATED',
  USER_DEACTIVATED: 'USER_DEACTIVATED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  CONTENT_HIDDEN: 'CONTENT_HIDDEN',
  CONTENT_RESTORED: 'CONTENT_RESTORED',
  CONTENT_REMOVED: 'CONTENT_REMOVED',
  REPORT_SUBMITTED: 'REPORT_SUBMITTED',
  REPORT_REVIEWED: 'REPORT_REVIEWED',
}

/**
 * The canonical vocabulary, for validation and documentation.
 * @returns {string[]}
 */
export function listAuditActions() {
  return Object.values(AUDIT_ACTIONS)
}